version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:  

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: practic73/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media
  frontend:
    image: practic73/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: practic73/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - media:/app/media
    ports:
      - 8000:80
